# Generated by Django 4.2 on 2024-11-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.PositiveIntegerField(choices=[(1, 'audio'), (2, 'pdf'), (3, 'video')], default=1),
        ),
    ]
