# Generated by Django 4.2 on 2024-11-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_file_file_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='parent',
            new_name='product',
        ),
    ]
